#!/usr/bin/env bash

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/tailscale/functions"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

declare APP="$1"

if [[ -n "$(tailscale_is_running_for_app)" ]]; then
  echo "http://${APP}"
  tailscale_serve_url
fi
