#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

trigger-tailscale-install() {
    storagedir="${DOKKU_LIB_ROOT}/data/tailscale"
    mkdir -p $storagedir

    # Install is potentially done by root.
    chown dokku:dokku $storagedir
}

trigger-tailscale-install "$@"
