#!/usr/bin/env bash
#
# dokku apps:destroy <APP>

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/tailscale/functions"

declare APP="$1"

dokku_log_info1 "cleaning up tailscale resources for $APP"
tailscale_down
