#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/tailscale/functions"

cmd-tailscale-down() {
  declare desc="removes an app from the tailnet"
  declare cmd="tailscale:down"
  [[ "$1" == "$cmd" ]] && shift 1

  declare APP="$1"

  tailscale_down
}

cmd-tailscale-down "$@"
