#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/tailscale/functions"

cmd-tailscale-down() {
  declare desc="removes an app or service from the tailnet"
  declare cmd="tailscale:down"
  [[ "$1" == "$cmd" ]] && shift 1

  # Parse --service flag
  if [[ "$1" == "--service" ]]; then
    shift 1
    parse_service_flag "$1"
  else
    declare APP="$1"
    export APP
  fi

  tailscale_down
}

cmd-tailscale-down "$@"
