#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/tailscale/functions"

cmd-tailscale-serve() {
  declare desc="serve the provided port over https for an app or service"
  declare cmd="tailscale:serve"
  [[ "$1" == "$cmd" ]] && shift 1

  # Parse --service flag
  if [[ "$1" == "--service" ]]; then
    shift 1
    parse_service_flag "$1"; shift 1; declare PORT="$1"
  else
    declare APP="$1" PORT="$2"
    export APP
  fi

  if [[ "$PORT" == "stop" ]]; then
    tailscale_serve_stop
  else
    tailscale_serve_start
  fi
}

cmd-tailscale-serve "$@"
