#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/tailscale/functions"

cmd-tailscale-up() {
  declare desc="adds an app or service to the tailnet"
  declare cmd="tailscale:up"
  [[ "$1" == "$cmd" ]] && shift 1

  # Parse --service flag
  if [[ "$1" == "--service" ]]; then
    shift 1
    parse_service_flag "$1"
  else
    declare APP="$1"
    export APP
  fi

  tailscale_up
}

cmd-tailscale-up "$@"
