#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$PLUGIN_AVAILABLE_PATH/tailscale/functions"

cmd-tailscale-up() {
  declare desc="adds an app to the tailnet"
  declare cmd="tailscale:up"
  [[ "$1" == "$cmd" ]] && shift 1

  declare APP="$1"

  tailscale_up
}

cmd-tailscale-up "$@"
